import { Message } from "@/components/ui/MessageCard";

// Dynamic billing period
const now = new Date();
const periodStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);

export const mockMessages: Message[] = [
  {
    id: "1",
    username: "@glowbysarah",
    platform: "instagram",
    comment: "Do you offer hydrafacials? How much do they cost?",
    aiReply: "Yes! Our HydraFacials start at $149 and include a full cleanse, extract, and hydration treatment. Want me to send you the booking link? 💜",
    status: "review",
    confidenceScore: 94,
    detectedIntent: "Service Inquiry",
    tags: ["Hot Lead", "Pricing Question", "Booking Intent"],
    timestamp: "2 min ago",
  },
  {
    id: "2",
    username: "@fitnessjunkie99",
    platform: "instagram",
    comment: "Do you offer payment plans?",
    aiReply: "Absolutely! We offer flexible 3 and 6-month payment plans with 0% interest. Send us a DM and we'll get you set up right away 🙌",
    status: "review",
    confidenceScore: 88,
    detectedIntent: "Pricing Question",
    tags: ["Hot Lead", "Pricing Question"],
    timestamp: "5 min ago",
  },
  {
    id: "3",
    username: "@luxe.brows",
    platform: "facebook",
    comment: "What's your availability this week for a brow appointment?",
    aiReply: "We have openings Tuesday through Friday! What time works best for you? DM us and we'll get you booked 🗓",
    status: "auto",
    confidenceScore: 97,
    detectedIntent: "Booking Intent",
    tags: ["Booking Intent"],
    timestamp: "12 min ago",
  },
  {
    id: "4",
    username: "@momof3beauty",
    platform: "instagram",
    comment: "Is this safe for sensitive skin? I've had reactions before.",
    aiReply: "Great question! All our treatments are formulated for sensitive skin and we do a patch test before every session. We recommend starting with a free consultation — DM us to book!",
    status: "review",
    confidenceScore: 79,
    detectedIntent: "Safety Concern",
    tags: ["General Inquiry", "Complaint Risk"],
    timestamp: "18 min ago",
  },
  {
    id: "5",
    username: "@agencyowner_mark",
    platform: "instagram",
    comment: "What's your pricing for bulk packages? We have 10 clients who might be interested.",
    aiReply: "We love working with agencies! Our bulk packages start at $499/mo for up to 10 accounts. DM us for a custom quote and we'll build something that works for your team.",
    status: "auto",
    confidenceScore: 91,
    detectedIntent: "B2B Inquiry",
    tags: ["Hot Lead", "Pricing Question"],
    timestamp: "25 min ago",
  },
  {
    id: "6",
    username: "@beautycoach_jen",
    platform: "instagram",
    comment: "Can I refer clients and earn a commission?",
    aiReply: "Yes! Our referral program gives you 15% on every client you send our way. DM us to get your unique referral link — it takes 2 minutes to set up 🎯",
    status: "auto",
    confidenceScore: 96,
    detectedIntent: "Partnership",
    tags: ["Hot Lead"],
    timestamp: "31 min ago",
  },
  {
    id: "7",
    username: "@skincarequeen_LA",
    platform: "facebook",
    comment: "This is such a scam. You charged me twice and never replied.",
    aiReply: "We're so sorry to hear this happened! This is absolutely not the experience we want for you. Our billing team will review your account immediately — can you DM us your email so we can prioritize this?",
    status: "escalated",
    confidenceScore: 45,
    detectedIntent: "Complaint",
    tags: ["Complaint Risk"],
    timestamp: "45 min ago",
  },
  {
    id: "8",
    username: "@wellness.coach",
    platform: "instagram",
    comment: "How does the AI reply system work exactly? I'm worried about it sounding robotic.",
    aiReply: "Great question! Our AI learns your exact brand voice, tone, and offers — then you review every reply before it posts. Nothing goes live without your approval. Want to see a demo? 🤖✨",
    status: "review",
    confidenceScore: 85,
    detectedIntent: "Product Curiosity",
    tags: ["Pricing Question"],
    timestamp: "1 hr ago",
  },
  {
    id: "9",
    username: "@diva_studios",
    platform: "instagram",
    comment: "Is there a free trial?",
    aiReply: "Yes! We offer a 14-day free trial — no credit card required. You can set up your brand voice, connect Instagram, and see real results before paying a cent. Start here: autom8.app 🚀",
    status: "auto",
    confidenceScore: 98,
    detectedIntent: "Trial Interest",
    tags: ["Hot Lead", "Booking Intent"],
    timestamp: "1 hr ago",
  },
  {
    id: "10",
    username: "@bossbabes_nyc",
    platform: "instagram",
    comment: "Does this work for Facebook too?",
    aiReply: "Yes! Autom8 works for both Instagram and Facebook comments from one dashboard. You can manage multiple accounts and see all your replies in one place.",
    status: "auto",
    confidenceScore: 99,
    detectedIntent: "Product Feature",
    tags: ["General Inquiry"],
    timestamp: "2 hr ago",
  },
  {
    id: "11",
    username: "@medspa_miami",
    platform: "instagram",
    comment: "How many replies per month on the basic plan?",
    aiReply: "Our Growth plan includes 1,000 replies/month — enough for most active accounts. Need more? Our Scale plan handles unlimited. Check our pricing: autom8.app/billing 💪",
    status: "auto",
    confidenceScore: 93,
    detectedIntent: "Pricing Question",
    tags: ["Pricing Question"],
    timestamp: "2 hr ago",
  },
  {
    id: "12",
    username: "@skinbykatrina",
    platform: "facebook",
    comment: "Is my data safe? What do you do with my Instagram info?",
    aiReply: "Your data is 100% secure. We use enterprise-grade encryption and only request the minimum permissions needed to read comments and post replies. We never sell your data. Privacy is our top priority.",
    status: "sent",
    confidenceScore: 88,
    detectedIntent: "Trust & Safety",
    tags: ["General Inquiry"],
    timestamp: "3 hr ago",
  },
];

export const mockUsage = {
  repliesUsed: 340,
  limit: 500,
  periodStart,
  periodEnd,
  dailyCounts: [8,12,5,14,18,22,9,11,16,20,13,7,19,24,17,21,15,10,23,18,12,25,14,9,16,20,11,8,18,15],
};

export const mockPlans = [
  {
    id: "starter",
    name: "Starter",
    price: 9,
    period: "week",
    replyLimit: 250,
    features: ["250 AI replies/month", "1 Instagram account", "Basic brand voice", "Human review queue", "Email support"],
    popular: false,
  },
  {
    id: "growth",
    name: "Growth",
    price: 29,
    period: "week",
    replyLimit: 1000,
    features: ["1,000 AI replies/month", "3 accounts (IG + FB)", "Advanced Brand Brain", "Priority review queue", "Analytics dashboard", "Priority support"],
    popular: true,
  },
  {
    id: "scale",
    name: "Scale",
    price: 99,
    period: "week",
    replyLimit: -1,
    features: ["Unlimited replies", "Unlimited accounts", "Multi-client dashboard", "White-label options", "Dedicated account manager", "API access"],
    popular: false,
  },
];

export const mockBrandProfile = {
  businessName: "Luxe Glow Medspa",
  industry: "medspa",
  websiteUrl: "https://luxeglow.com",
  description: "Premier medical spa in Los Angeles offering HydraFacials, Botox, laser treatments, and wellness services.",
  tones: ["Professional", "Luxe", "Friendly"],
  customToneNotes: "Warm and welcoming but always professional. Never use slang. Always end with a CTA.",
  services: [
    { name: "HydraFacial", priceRange: "$149 - $249" },
    { name: "Botox", priceRange: "$12/unit" },
    { name: "Laser Hair Removal", priceRange: "$199+" },
  ],
  ctaKeywords: ["price", "how much", "cost", "available", "book", "appointment", "free trial"],
  escalationRules: "Do not discuss specific medical conditions, diagnoses, or treatment outcomes. Escalate complaints or negative experiences to human team.",
  emojiAllowed: true,
  language: "English",
  formalityLevel: 65,
};

export const mockUser = {
  id: "mock-user-id",
  name: "Demo User",
  email: "demo@autom8.app",
  plan: "starter" as const,
  connectedInstagram: false,
  brandSetupComplete: true,
};

export const mockActivityFeed = [
  { id: "1", text: "Auto-replied to @glowbysarah on Instagram", time: "2 min ago", type: "reply" },
  { id: "2", text: "@agencyowner_mark opened the booking link you shared", time: "8 min ago", type: "lead" },
  { id: "3", text: "7 new comments received from your last post", time: "15 min ago", type: "inbox" },
  { id: "4", text: "@skincarequeen_LA escalated — needs human review", time: "45 min ago", type: "escalation" },
  { id: "5", text: "Auto-replied to 12 comments overnight", time: "8 hr ago", type: "reply" },
];
